### ISSUE TITLE
Exposed server address, username and password

### ISSUE THREAD

**Issue by Zallist** [immi5556/Immanuel.KeyValue#2]
https://github.com/immi5556/Immanuel.KeyValue/blob/c0dd87b2304e1998fcfecbe12a751b7fb717f267/Immanuel.KeyValue/Controllers/KeyValController.cs#L24

Title says it all.

**Comment by ir-dev** [comment]
revisiting, after few years. starting to fix now.

**Comment by ir-dev** [comment]
resolved
